name: PolicyFund Collector

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 1시
  workflow_dispatch:    # 수동 실행 가능

jobs:
  collect:
    runs-on: ubuntu-latest
    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: 체크아웃 코드
        uses: actions/checkout@v3

      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install requests pymysql

      - name: 정책자금 수집
        run: python collector_gh.py
